### ISSUE TITLE
알고리즘 관리 건의

### ISSUE THREAD

**Issue by ghost** [mukhoplus/BOJ#1]
승와이 깃헙 몰래 놀러왔는데
이거 관리 좀만 잘하면 좋을거 같거등 :)

@kbpark9898 밑에 기범이 레포 참고해서 문제 종류별로 분류하면 나중에 참고하기 편할 듯!!
https://github.com/kbpark9898/Algorithm_Solving

**Comment by mukhoplus** [comment]
처음엔 100일 연속 공부였다가 휴가 때부터 100일 연속 채우기에 급급한 상황이라,,
이제 시간 여유 생겼으니 한번 야무지게 정리하는 시간 가져보도록 하겠읍니다,,,
^^7

**Comment by ghost** [comment]
빠이팅 :)
